openapi: 3.0.0
info:
  title: Sample REST API
  version: 1.0.0
  description: A simple REST API example using OpenAPI schema in YAML.

paths:
  /users:
    get:
      summary: Retrieve a list of users
      description: Retrieve a list of all users in the system.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The user's unique identifier.
                    username:
                      type: string
                      description: The user's username.
                    email:
                      type: string
                      format: email
                      description: The user's email address.

  /users/{userId}:
    get:
      summary: Retrieve user by ID
      description: Retrieve information about a specific user by their ID.
      parameters:
        - name: userId
          in: path
          description: The ID of the user to retrieve.
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The user's unique identifier.
                  username:
                    type: string
                    description: The user's username.
                  email:
                    type: string
                    format: email
                    description: The user's email address.
        '404':
          description: User not found

