name: Deploy OpenAPI Documentation

on:
  push:
    branches:
      - main  # Adjust this branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Choose the Node.js version you need

      - name: Install Redoc CLI
        run: npm install -g redoc-cli

      - name: Generate HTML Documentation
        run: redoc-cli bundle api.yaml --output docs/index.html
        # Replace "openapi.yaml" with the name of your OpenAPI YAML file and adjust the output path as needed

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Update OpenAPI documentation"
          git push
